// GENERAL_ACCESS
exports.ABSOLUTE = "ABSOLUTE";
exports.ADMINISTRATOR = "ADMINISTRATOR";

// STORE_GENERAL_ACCESS
exports.STORE_OWNER = "STORE_OWNER";
exports.STORE_ADMINISTRATOR = "STORE_ADMINISTRATOR";

// DASHBOARD_ACCESS
exports.VIEW_HOME = "VIEW_HOME";
exports.VIEW_PURCHASE_ORDER = "VIEW_PURCHASE_ORDER";
exports.VIEW_PINNED = "VIEW_PINNED";
exports.VIEW_CATALOGUES = "VIEW_CATALOGUES";
exports.ADD_STORE = "ADD_STORE";
exports.ADD_CATALOGUE = "ADD_CATALOGUE";

// CREATIVE_STORE_ACCESS
exports.VIEW_CHANNEL = "VIEW_CHANNEL";
exports.SEND_MESSAGES = "SEND_MESSAGES";
