// GENERAL
exports.SUCCESS = "SUCCESS";
exports.STORE_PROFILE_PICTURE = "STORE_PROFILE_PICTURE";
exports.PRODUCT_CATALOGUE_IMAGE = "PRODUCT_CATALOGUE_IMAGE";
exports.PRODUCT_CATALOGUE_ADDITIONAL_FILES =
  "PRODUCT_CATALOGUE_ADDITIONAL_FILES";

// ROLES
exports.USER = "USER";

// MULTER NAMES
exports.UPLOADED_IMAGE_FILES = "uploadedImageFiles";
exports.UPLOADED_ADDITIONAL_FILES =
  "uploadedAdditionalFiles";
exports.UPLOADED_STORE_PROFILE_PICTURE =
  "uploadedStoreProfilePicture";

// PREFIXES
exports.STR = "STR"; // this is the prefix for store code
exports.PRD = "PRD"; // this is the prefix for product code
exports.CLOG = "CLOG"; // this is the prefix for catalogue code

// AXIOS
exports.POST = "POST";
exports.GET = "GET";

// AXIOS LOG TITLE
exports.GET_CHECK_AUTH_TOKEN = "GET_CHECK_AUTH_TOKEN";
exports.POST_SEND_PROFILEPIC = "POST_SEND_PROFILEPIC";
exports.POST_ADD_CATALOGUE = "POST_ADD_CATALOGUE";
exports.POST_UPLOAD_FILES = "POST_UPLOAD_FILES";

// HEADER NAME
exports.X_SID = "x-sid";
exports.AUTHORIZATION = "authorization";
exports.CONTENT_TYPE = "Content-Type";

// EMAIL SUBJECT
exports.OTP_EMAIL =
  "Account Registration - Berikut adalah nomor OTPmu, jangan disebar ya !";

// API URLs
exports.CHECK_AUTH_TOKEN = `/v1/auth/check`;
exports.UPLOAD_FILES = `/v1/files/upload`;

// DEFAULT VALUES
exports.PROVINCE_DEFAULT_VALUE = "PILIH PROVINSI";
exports.REGENCY_DEFAULT_VALUE = "PILIH KOTA";
exports.DISTRICT_DEFAULT_VALUE = "PILIH KECAMATAN";
exports.VILLAGE_DEFAULT_VALUE = "PILIH KELURAHAN";

// OTHERS
exports.EMPTY_STRING = "";
exports.ALPHABETH_CHAR_AND_NUMBER =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

// STATUSES
exports.ACTIVE = "ACTIVE";
exports.NON_ACTIVE = "NON_ACTIVE";
exports.DELETED = "DELETED";

// ACTIVITY REPORT STATUS
exports.NEW_REPORT = "NEW_REPORT";
exports.IN_PROGRESS = "IN_PROGRESS";
exports.WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL";
exports.REPORT_SOLVED = "REPORT_SOLVED";
exports.REPORT_CANCELED = "REPORT_CANCELED";

// TRANSACTION STATUS
exports.PENDING_PAYMENT = "PENDING_PAYMENT";
exports.READY_TO_SHIP = "READY_TO_SHIP";
exports.ON_SHIPMENT = "ON_SHIPMENT";
exports.RETURN_REQUEST = "RETURN_REQUEST";
exports.ON_RETURN = "ON_RETURN";
exports.TRANSACTION_COMPLETE = "TRANSACTION_COMPLETE";
exports.TRANSACTION_CANCELED = "TRANSACTION_CANCELED";

// ACTIVITY REPORT TYPE
exports.REPORT_USER = "REPORT_USER";
exports.REPORT_STORE = "REPORT_STORE";
exports.REPORT_SHIPMENT_RETURN = "REPORT_SHIPMENT_RETURN";

// TRANSACTION TYPE
exports.B2C_TRANSACTION = "B2C_TRANSACTION";
exports.FUND_TRANSFER = "FUND_TRANSFER";
exports.FUND_LIQUIDATION = "FUND_LIQUIDATION";

// ACCESS TYPE
exports.GENERAL_ACCESS = "GENERAL_ACCESS";
exports.DASHBOARD_ACCESS = "DASHBOARD_ACCESS";
exports.CREATIVE_STORE_ACCESS = "CREATIVE_STORE_ACCESS";
